---
title: "DV"
author: "diao1010"
date: "2017/8/20"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## 資料視覺化Miscellaneous Graphs

### Correlation matrix
```{r}
#Correlation matrix
library("ggplot2")
library("corrplot")
library("gcookbook")
mcor <- cor(mtcars)
round(mcor, digits=2)
corrplot(mcor)

#自訂顏色
col <- colorRampPalette(c("red", "white", "blue"))
corrplot(mcor, method="number", shade.col=NA, tl.col="black", tl.srt=45,
      	col=col(200))
```
  
##Network graph
```{r}
library(igraph)
 
gd <- graph(c(1,2, 2,3, 2,4, 1,4, 5,5, 3,6))
plot(gd)

g <- graph.data.frame(madmen, directed=TRUE)
par(mar=c(0,0,0,0))
plot(g, layout=layout.fruchterman.reingold, vertex.size=8,    	
     edge.arrow.size=0.5, vertex.label=NA)
 
m <- madmen[1:nrow(madmen) %% 2 == 1, ]
g <- graph.data.frame(m, directed=FALSE)
plot(g, layout=layout.fruchterman.reingold,
 	vertex.size = 4,
 	vertex.label = V(g)$name,
 	vertex.label.cex = 0.8,
 	vertex.label.dist = 0.4,
 	vertex.label.color = "black")
 
```
## Heat map
```{r} 
presidents
str(presidents)
pres_rating <- data.frame(
     rating = as.numeric(presidents),
     year = as.numeric(floor(time(presidents))),
     quarter = as.numeric(cycle(presidents))
   	)
p <- ggplot(pres_rating, aes(x=year, y=quarter, fill=rating))

p + geom_tile() +
   	scale_x_continuous(breaks = seq(1940, 1976, by = 4)) +
   	scale_y_reverse() +
   	scale_fill_gradient2(midpoint=50, mid="grey70", limits=c(0,100))
``` 
## Dendrogram
```{r}
hc <- hclust(dist(USArrests), method="ave")
plot(hc, hang = -1)
```
## Mosaic plot
```{r}
library(grid)
library(vcd)
UCBAdmissions
ftable(UCBAdmissions)
mosaic( ~ Admit + Gender + Dept, data=UCBAdmissions)
 
 
mosaic( ~ Dept + Gender + Admit, data=UCBAdmissions,
          	highlighting="Admit", highlighting_fill=c("lightblue", "pink"),
            	direction=c("v","h","v"))
```
## Pie chart
```{r}
library(MASS)
fold <- table(survey$Fold)
fold
pie(fold)
pie(c(99, 18, 100), labels=c("L on R", "Neither", "R on L"))
```
## Map
```{r}
library(maps)
library(mapproj)
 
map("state")
states_map <- map_data("state")
ggplot(states_map, aes(x=long, y=lat, group=group)) +
  geom_polygon(fill="white", colour="black")
 
ggplot(states_map, aes(x=long, y=lat, group=group)) +
  geom_path() + coord_map("mercator")
 
east_asia<- map_data("world", region=c("Japan", "China", "North Korea",                                        "South Korea","Taiwan"))
ggplot(east_asia, aes(x=long, y=lat, group=group, fill=region)) +
  geom_polygon(colour="black") +
  scale_fill_brewer(palette="Set2")
 
nz1 <- map_data("world", region="New Zealand")
nz1 <- subset(nz1, long > 0 & lat > -48)
ggplot(nz1, aes(x=long, y=lat, group=group)) + geom_path()
 
``` 
##Choropleth Map
```{r}
crimes <- data.frame(state = tolower(rownames(USArrests)), USArrests)
states_map <- map_data("state")
 
crime_map <- merge(states_map, crimes, by.x="region", by.y="state")
head(crime_map)
 
# For arrange() function
library(plyr)
# Sort by group, then order
crime_map <- arrange(crime_map, group, order)
 
ggplot(crimes, aes(map_id = state, fill=Assault)) +
  geom_map(map = states_map, colour="black") +
  scale_fill_gradient2(low="#559999", mid="grey90", high="#BB650B",
                       midpoint=median(crimes$Assault)) +
  expand_limits(x = states_map$long, y = states_map$lat) +
  coord_map("polyconic")
 


```

